// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import AVFoundation;
@import Foundation;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class AVCaptureDevice;
@class AVCaptureDeviceInput;

SWIFT_CLASS("_TtC13rtmpStreaming23AVCaptureSessionManager")
@interface AVCaptureSessionManager : NSObject
+ (AVCaptureDevice * __nullable)deviceWithPosition:(AVCaptureDevicePosition)position;
+ (int32_t)defaultFPS;
+ (NSString * __nonnull)defaultSessionPreset;
+ (NSDictionary * __nonnull)defaultVideoSettings;
@property (nonatomic) int32_t FPS;
@property (nonatomic) AVCaptureVideoOrientation orientation;
@property (nonatomic) BOOL torch;
@property (nonatomic) BOOL continuousAutofocus;
@property (nonatomic) BOOL continuousExposure;
@property (nonatomic) BOOL syncOrientation;
@property (nonatomic, copy) NSString * __nonnull sessionPreset;
@property (nonatomic, copy) NSDictionary * __nonnull videoSettings;
@property (nonatomic, readonly, strong) AVCaptureDeviceInput * __nullable currentAudio;
@property (nonatomic, readonly, strong) AVCaptureDeviceInput * __nullable currentCamera;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)attachAudio:(AVCaptureDevice * __nullable)audio;
- (void)attachCamera:(AVCaptureDevice * __nullable)camera;
@end


@interface AVCaptureSessionManager (SWIFT_EXTENSION(rtmpStreaming))
- (void)startRunning;
- (void)stopRunning;
@end


SWIFT_CLASS("_TtC13rtmpStreaming19AudioStreamPlayback")
@interface AudioStreamPlayback : NSObject
@property (nonatomic, readonly) BOOL running;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AudioStreamPlayback (SWIFT_EXTENSION(rtmpStreaming))
- (void)startRunning;
- (void)stopRunning;
@end

@class NSNotification;

SWIFT_CLASS("_TtC13rtmpStreaming5Event")
@interface Event : NSObject
+ (NSString * __nonnull)SYNC;
+ (NSString * __nonnull)RTMP_STATUS;
+ (Event * __nonnull)from:(NSNotification * __nonnull)notification;
@property (nonatomic, readonly, copy) NSString * __nonnull type;
@property (nonatomic, readonly) BOOL bubbles;
@property (nonatomic, readonly, strong) id __nullable target;
@end


SWIFT_CLASS("_TtC13rtmpStreaming15EventDispatcher")
@interface EventDispatcher : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTarget:(id __nonnull)target OBJC_DESIGNATED_INITIALIZER;
- (void)addEventListener:(NSString * __nonnull)type selector:(SEL __null_unspecified)selector;
- (void)addEventListener:(NSString * __nonnull)type selector:(SEL __null_unspecified)selector observer:(id __nonnull)observer;
- (void)addEventListener:(NSString * __nonnull)type selector:(SEL __null_unspecified)selector observer:(id __nonnull)observer useCapture:(BOOL)useCapture;
- (void)removeEventListener:(NSString * __nonnull)type selector:(SEL __null_unspecified)selector;
- (void)removeEventListener:(NSString * __nonnull)type selector:(SEL __null_unspecified)selector observer:(id __nonnull)observer;
- (void)removeEventListener:(NSString * __nonnull)type selector:(SEL __null_unspecified)selector observer:(id __nonnull)observer useCapture:(BOOL)useCapture;
- (void)dispatchEvent:(Event * __nonnull)e;
@end


@interface NSURL (SWIFT_EXTENSION(rtmpStreaming))
@end


SWIFT_CLASS("_TtC13rtmpStreaming14RTMPConnection")
@interface RTMPConnection : EventDispatcher
@property (nonatomic, copy) NSString * __nullable swfUrl;
@property (nonatomic, copy) NSString * __nullable pageUrl;
@property (nonatomic, copy) NSString * __nonnull flashVer;
@property (nonatomic, readonly, strong) NSURL * __nullable uri;
@property (nonatomic, readonly) BOOL connected;
@property (nonatomic) uint8_t objectEncoding;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)close;
@end


@interface RTMPConnection (SWIFT_EXTENSION(rtmpStreaming))
@end


SWIFT_CLASS("_TtC13rtmpStreaming16RTMPSharedObject")
@interface RTMPSharedObject : EventDispatcher
+ (RTMPSharedObject * __nonnull)getRemote:(NSString * __nonnull)name remotePath:(NSString * __nonnull)remotePath persistence:(BOOL)persistence;
@property (nonatomic, readonly) uint8_t objectEncoding;
@property (nonatomic, readonly, copy) NSString * __nonnull description;
- (void)connect:(RTMPConnection * __nonnull)rtmpConnection;
- (void)clear;
- (void)close;
@end

@class UIView;
@class VisualEffect;

SWIFT_CLASS("_TtC13rtmpStreaming10RTMPStream")
@interface RTMPStream : EventDispatcher
+ (NSString * __nonnull)rootPath;
+ (void)setRootPath:(NSString * __nonnull)value;
+ (uint32_t)defaultAudioBitrate;
+ (uint32_t)defaultVideoBitrate;
@property (nonatomic, readonly) uint8_t objectEncoding;
@property (nonatomic) BOOL torch;
@property (nonatomic) BOOL syncOrientation;
@property (nonatomic, readonly, strong) UIView * __null_unspecified view;
@property (nonatomic, copy) NSString * __null_unspecified videoGravity;
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nonnull audioSettings;
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nonnull videoSettings;
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nonnull captureSettings;
- (nonnull instancetype)initWithRtmpConnection:(RTMPConnection * __nonnull)rtmpConnection OBJC_DESIGNATED_INITIALIZER;
- (void)attachAudio:(AVCaptureDevice * __nullable)audio;
- (void)attachCamera:(AVCaptureDevice * __nullable)camera;
- (void)receiveAudio:(BOOL)flag;
- (void)receiveVideo:(BOOL)flag;
- (void)publish:(NSString * __nullable)name;
- (void)seek:(double)offset;
- (void)publish:(NSString * __nullable)name type:(NSString * __nonnull)type;
- (void)close;
- (BOOL)registerEffectWithVideo:(VisualEffect * __nonnull)effect;
- (BOOL)unregisterEffectWithVideo:(VisualEffect * __nonnull)effect;
- (void)setPointOfInterest:(CGPoint)focus exposure:(CGPoint)exposure;
- (void)observeValueForKeyPath:(NSString * __nullable)keyPath ofObject:(id __nullable)object change:(NSDictionary<NSString *, id> * __nullable)change context:(void * __null_unspecified)context;
@end


@interface RTMPStream (SWIFT_EXTENSION(rtmpStreaming))
@end


SWIFT_CLASS("_TtC13rtmpStreaming9Responder")
@interface Responder : NSObject
@end

@class NSString;
@class CADisplayLink;

SWIFT_CLASS("_TtC13rtmpStreaming20ScreenCaptureSession")
@interface ScreenCaptureSession : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, NSObject *> * __nonnull attributes;
- (void)onScreen:(CADisplayLink * __nonnull)displayLink;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ScreenCaptureSession (SWIFT_EXTENSION(rtmpStreaming))
- (void)startRunning;
- (void)stopRunning;
@end

@class CIImage;

SWIFT_CLASS("_TtC13rtmpStreaming12VisualEffect")
@interface VisualEffect : NSObject
- (CIImage * __nonnull)execute:(CIImage * __nonnull)image;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
